name: Release Flow

on:
  push:
    branches: [ "main", "qa", "staging" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    outputs:
      created-pr: ${{ steps.prepare-release.outputs.pr }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Delete old changelog
        run: rm -f CHANGELOG.md

      - name: Create Release PR
        id: prepare-release
        uses: googleapis/release-please-action@v4
        with:
          # release-type: node should not be defined when using manifest file
          target-branch: ${{ github.ref_name }}
          skip-github-release: true
          config-file: .github/config/release-please-config-${{ github.ref_name }}.json
          manifest-file: .github/config/release-please-manifest-${{ github.ref_name }}.json

      - name: Show release
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.prepare-release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq

  deploy:
    runs-on: ubuntu-latest
    needs: create-pr
    if: ${{ !needs.create-pr.outputs.created-pr }}
    steps:
      - name: Deploy
        run: echo "Deploying..."

  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # release-type: node should not be defined when using manifest file
          target-branch: ${{ github.ref_name }}
          skip-github-pull-request: true
          config-file: .github/config/release-please-config-${{ github.ref_name }}.json
          manifest-file: .github/config/release-please-manifest-${{ github.ref_name }}.json
      
      - name: Show release
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq
